### PR TITLE
Create give_all_groups_access_to_all_modules.sql

### PR DESCRIPTION
**Pull request by DelecroixQuentin**
SQL to allow all groups access to all modules

### CODE REVIEW

**Comment by SebSept** [comment]
Does the table need to empty before processing ? (because of duplicate primary)

**Comment by DelecroixQuentin** [comment]
Hi,

Oh, yes, it is necessary to empty the table before launching the query.
Do I have to add the truncate ?

**Comment by SebSept** [comment]
You can just leave a comment in the sql file, add the truncate statement or use an 'insert ignore' (I guess it work).
As you like ...

**Comment by jf-viguier** [comment]
I prefer insert ignore instead of truncate, less brutal

**Review by SebSept — APPROVED** [review]
Ok for me (not tested)

**Comment by jf-viguier** [comment]
Thanks @DelecroixQuentin

**Pull request merged**
