### PR TITLE
get sales ( total and quantity ) by ipa

### PR DESCRIPTION
**Pull request by okom3pom**

### CODE REVIEW

**Review by SebSept — COMMENTED** [review]
Thanks for contribution :+1: 

I tested on database with products not having 'product_attributes', I get a single row for all products.

Maybe it's possible to filter products with product_attribute_id = 0 or at least add a warning note.

**Comment by okom3pom** [comment]
Hi,

I don't have product with no ipa can you try : 

```
set @date_from="2020-01-01 00:00:00";
set @date_to="2020-01-30 00:00:00";
set @need_invoice = 1;
set @no_product_return = 1;

SELECT od.product_name, od.product_reference, od.product_attribute_id, SUM(od.`product_quantity`) as qty, SUM(od.`total_price_tax_incl`) as total, p.wholesale_price FROM `ps_order_detail` od 

INNER JOIN `ps_orders` o ON od.id_order = o.id_order 

INNER JOIN `ps_product` p ON p.id_product = od.product_id

WHERE 

( CASE o.invoice_date

    WHEN @need_invoice = 1 THEN o.invoice_date > @date_from AND o.invoice_date < @date_to

    ELSE o.date_add > @date_from AND o.date_add < @date_to

END )

GROUP BY case when product_attribute_id > 0
              then od.product_attribute_id
              else od.product_id
         end

ORDER BY p.id_product
```

If it's good i update the file

**Comment by okom3pom** [comment]
This one work for me : 

LoL i runed the query with 2014 to 2020 for to find a product without IPA; query time so long 

```
set @date_from="2020-01-01 00:00:00";
set @date_to="2020-01-30 00:00:00";
set @need_invoice = 1;
set @no_product_return = 1;

SELECT od.product_name, od.product_reference, od.product_attribute_id, SUM(od.`product_quantity`) as qty, SUM(od.`total_price_tax_incl`) as total, p.wholesale_price FROM `ps_order_detail` od 

INNER JOIN `ps_orders` o ON od.id_order = o.id_order 

INNER JOIN `ps_product` p ON p.id_product = od.product_id

WHERE 

( CASE o.invoice_date

    WHEN @need_invoice = 1 THEN o.invoice_date > @date_from AND o.invoice_date < @date_to

    ELSE o.date_add > @date_from AND o.date_add < @date_to

END )

AND

( CASE od.product_quantity_return

    WHEN @no_product_return = 1 THEN od.product_quantity_return = 0

    ELSE 1=1

END )

GROUP BY CASE WHEN product_attribute_id > 0
              THEN od.product_attribute_id
              ELSE od.product_id
         END

ORDER BY od.product_attribute_id ASC
```

**Comment by SebSept** [comment]
nice, it work with and without product_attributes.

I suggest to add the product_id column and order by product_id then product_attribute id.

This results in :
```mysql
set @date_from = "2020-10-01 00:00:00";
set @date_to = "2020-11-30 00:00:00";
set @need_invoice = 1;
set @no_product_return = 1;

SELECT od.product_id,
       od.product_name,
       od.product_reference,
       od.product_attribute_id,
       SUM(od.`product_quantity`)     as qty,
       SUM(od.`total_price_tax_incl`) as total,
       p.wholesale_price
FROM `ps_order_detail` od
         INNER JOIN `ps_orders` o ON od.id_order = o.id_order
         INNER JOIN `ps_product` p ON p.id_product = od.product_id
WHERE (CASE o.invoice_date
           WHEN @need_invoice = 1 THEN o.invoice_date > @date_from AND o.invoice_date < @date_to
           ELSE o.date_add > @date_from AND o.date_add < @date_to
    END)
  AND (CASE od.product_quantity_return
           WHEN @no_product_return = 1 THEN od.product_quantity_return = 0
           ELSE 1 = 1
    END)
GROUP BY CASE
             WHEN product_attribute_id > 0
                 THEN od.product_attribute_id
             ELSE od.product_id
             END
ORDER BY od.product_attribute_id, od.product_attribute_id ASC
```

Can you please add another commit with your and my modifications ?

**Comment by okom3pom** [comment]
Yes i do this but before i don't understand why my condition bug ... 

Normaly i can't have result with product_quantity_return 

When i run with : set @no_product_return = 1; 

Capture d’écran de 2020-11-24 13-03-23

When i run with : set @no_product_return = 0; 

Capture d’écran de 2020-11-24 13-04-48

**Comment by okom3pom** [comment]
Ok i found 

`CASE od.product_quantity_return`

Just `CASE `i dont' know why :p

**Review by SebSept — APPROVED** [review]
Tested with need_invoice & no_product_return at 1 or 0
Works fine.
(I did not check all results)

Very slow, but I think this is normal.
I don't know if speed it could be improved, maybe not.

A short description a bit longer would be perfect, but that's not mandatory for me.

Thanks :+1:

**Pull request merged**
